version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      workflow-actions:
        patterns:
          - "*"
    allow:
      - dependency-name: "actions/*"
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      build-dependencies:
        patterns:
          # Maven plugins:
          - "*maven*plugin*"
          - "org.apache.maven*:*"
          # Test dependencies:
          - "org.testng*"
    ignore:
      # We have a fixed major version of OpenJFX to work with the min JDK we require
      - dependency-name: "org.openjfx:*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
