#
# Jakarta Validation TCK
#
# License: Apache License, Version 2.0
# See the license.txt file in the root directory or <http://www.apache.org/licenses/LICENSE-2.0>.
#

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      workflow-actions:
        patterns:
          - "*"
    allow:
      - dependency-name: "actions/*"
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      build-dependencies:
        patterns:
          # Maven plugins:
          - "*maven*plugin*"
          - "org.apache.maven*:*"
          # Build dependencies:
          - "com.puppycrawl*"
          - "org.hibernate.infra*"
          # Test dependencies:
          - "org.testng*"
          - "org.jboss.arquillian*"
          - "org.jboss.shrinkwrap*"
          - "org.assertj*"
    ignore:
      # We have a fixed major version of OpenJFX to work with the min JDK we require
      - dependency-name: "org.openjfx:*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
