[[appeals-process]]
== Appeals Process

While the Bean Validation TCK is rigorous about enforcing an
implementation's conformance to the {jsrVersion} specification, it's
reasonable to assume that an implementor may discover new and/or better ways
to validate the assertions. This chapter covers the appeals process, defined
by the Specification Lead, Red Hat, Inc., which allows implementors of the
{jsrVersion} specification to challenge one or more tests defined by the
Bean Validation TCK.

The appeals process identifies who can make challenges to the TCK,
what challenges to the TCK may be submitted, how these challenges are
submitted, how and by whom challenges are addressed and how accepted
challenges to the TCK are managed.

Following the recent adoption of transparency in the JCP, implementors
are encouraged to make their appeals public, which this process facilitates.
The JCP community should recognize that issue reports are a central aspect
of any good software and it's only natural to point out shortcomings and
strive to make improvements. Despite this good faith, not all implementors
will be comfortable with a public appeals process. Instructions about how to
make a private appeal are therefore provided.

=== Who can make challenges to the TCK?

Any implementor may submit an appeal to challenge one or more tests
in the Bean Validation TCK. In fact, members of the {jsrVersion} Expert
Group (EG) encourage this level of participation.

=== What challenges to the TCK may be submitted?

Any test case (i.e. `@Test` method), test case
configuration (e.g. `@Deployment`, validation.xml),
test entities, annotations and other resources may be challenged by an
appeal.

What is generally not challengeable are the assertions made by the
specification. The specification document is controlled by a separate
process and challenges to it should be handled through the {jsrVersion} EG
by sending an e-mail to mailto:beanvalidation-tck@redhat.com[beanvalidation-tck@redhat.com].

=== How these challenges are submitted?

To submit a challenge, a new issue of type Bug should be created
against https://hibernate.atlassian.net/browse/BVTCK[BVTCK] in the
Hibernate JIRA instance. The appellant should complete the Summary,
Component (TCK Appeal), Environment and Description fields only. Any
communication regarding the issue should be added in the comments of the
issue for accurate record.

To submit an issue in the Hibernate JIRA, you must have a (free)
JIRA member account. You can create a member account using the https://hibernate.atlassian.net/secure/Signup!default.jspa[on-line
registration].

If you wish to make a private challenge, you should follow the above
procedure, setting the Security Level to Private. Only the issue reporter,
TCK Project Lead and designates will be able to view the issue. Should
there be need for clarification or discussions before actually entering a
bug into the issue tracker, an email can be sent to mailto:beanvalidation-tck@redhat.com[beanvalidation-tck@redhat.com].

=== How and by whom challenges are addressed?

The challenges will be addressed in a timely fashion by the Bean
Validation TCK Project Lead, as designated by Specification Lead, Red Hat,
Inc. or his/her designate. The appellant can also monitor the process by
watching the issue filed against https://hibernate.atlassian.net/browse/BVTCK[BVTCK].

The current TCK Project Lead is listed on the https://hibernate.atlassian.net/browse/BVTCK[BVTCK
Project Summary Page].

=== How accepted challenges to the TCK are managed?

Accepted challenges will be acknowledged via the filed issue's
comment section. Communication between the Bean Validation TCK Project
Lead and the appellant will take place via the issue comments. The issue's
status will be set to "Resolved" when the TCK project lead believes the
issue to be resolved. The appellant should, within 30 days, either close
the issue if they agree, or reopen the issue if they do not believe the
issue to be resolved.

Resolved issue not addressed for 30 days will be closed by the TCK
Project Lead. If the TCK Project Lead and appellant are unable to agree on
the issue resolution, it will be referred to the {jsrVersion}
specification lead or his/her designate.
