[[appeals-process]]
== Appeals Process

While the Jakarta Bean Validation TCK is rigorous about enforcing an implementation's conformance to the Jakarta Bean Validation specification,
it's reasonable to assume that an implementor may discover new and/or better ways to validate the assertions.
The appeals process is defined by the Jakarta EE https://github.com/jakartaee/specification-committee/blob/master/process.adoc[Jakarta EE TCK Process 1.0].

=== What challenges to the TCK may be submitted?

Any test case (i.e. `@Test` method), test case
configuration (e.g. `@Deployment`, validation.xml),
test entities, annotations and other resources may be challenged by an
appeal.

What is generally not challengeable are the assertions made by the
specification. The specification document is controlled by a separate
process and challenges to it should be handled through the Jakarta Bean Validation EG
by sending an e-mail to mailto:bean-validation-dev@eclipse.org[bean-validation-dev@eclipse.org].

=== How these challenges are submitted?

To submit a challenge, a new issue of type Bug should be created
against https://hibernate.atlassian.net/browse/BVTCK[BVTCK] in the
Hibernate JIRA instance. The appellant should complete the Summary,
Component (TCK Appeal), Environment and Description fields only. Any
communication regarding the issue should be added in the comments of the
issue for accurate record.

To submit an issue in the Hibernate JIRA, you must have a (free)
JIRA member account. You can create a member account using the https://hibernate.atlassian.net/secure/Signup!default.jspa[on-line
registration].

=== How and by whom challenges are addressed?

The challenges will be addressed in a timely fashion by the Bean Validation TCK Project Lead,
as designated by the Specification Lead, Red Hat Inc., or his/her designate.
The appellant can also monitor the process by
watching the issue filed against https://hibernate.atlassian.net/browse/BVTCK[BVTCK].

The current TCK Project Lead is listed on the https://jakarta.ee/specifications/bean-validation[Bean Validation Project Summary Page] on Jakarta EE.

=== How accepted challenges to the TCK are managed?

The workflow for TCK challenges is outlined in the https://github.com/jakartaee/specification-committee/blob/master/process.adoc[Jakarta EE TCK Process 1.0].

Periodically, an updated TCK will be released, containing tests altered due to challenges - no new tests will be added.
Implementations are required to pass the updated TCK.
This release stream is named 2.0.x, where x will be incremented.

Additionally, new tests will be added to the TCK improving coverage of the specification.
We encourage implementations to pass this TCK, however it is not required. This release stream is named 2.y.z where y &gt;= 1.
